In [45]:

from  keras.models  import Sequential
from keras.layers import Dense 
from keras.optimizers import Adam, SGD

%matplotlib inline
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

In [46]:
file = pd.read_csv('pulsar_stars.csv', error_bad_lines=False)

In [47]:
A=file[[' Mean of the integrated profile']].values
B=file[[' Standard deviation of the integrated profile']].values
C=file[[' Excess kurtosis of the integrated profile']].values
D=file[[' Skewness of the integrated profile']].values
E=file[[' Mean of the DM-SNR curve']].values
F=file[[' Standard deviation of the DM-SNR curve']].values
G=file[[' Excess kurtosis of the DM-SNR curve']].values
H=file[[' Skewness of the DM-SNR curve']].values
I=file[['target_class']].values

In [48]:
A

array([[140.5625   ],
       [102.5078125],
       [103.015625 ],
       ...,
       [119.3359375],
       [114.5078125],
       [ 57.0625   ]])

In [49]:
B

array([[55.68378214],
       [58.88243001],
       [39.34164944],
       ...,
       [59.93593941],
       [53.90239966],
       [85.79734025]])

In [50]:
C

array([[-0.23457141],
       [ 0.46531815],
       [ 0.32332837],
       ...,
       [ 0.1593631 ],
       [ 0.20116138],
       [ 1.40639105]])

In [51]:
D

array([[-0.6996484 ],
       [-0.51508791],
       [ 1.05116443],
       ...,
       [-0.7430254 ],
       [-0.02478884],
       [ 0.08951971]])

In [52]:
E

array([[  3.19983278],
       [  1.67725752],
       [  3.12123746],
       ...,
       [ 21.43060201],
       [  1.94648829],
       [188.3060201 ]])

In [53]:
F

array([[19.11042633],
       [14.86014572],
       [21.74466875],
       ...,
       [58.8720002 ],
       [13.38173065],
       [64.71256228]])

In [54]:
G

array([[ 7.97553179],
       [10.57648674],
       [ 7.73582202],
       ...,
       [ 2.49951714],
       [10.00796731],
       [-1.59752658]])

In [55]:
H

array([[ 74.24222492],
       [127.3935796 ],
       [ 63.17190911],
       ...,
       [  4.59517265],
       [134.2389095 ],
       [  1.42947536]])

In [56]:
I

array([[0],
       [0],
       [0],
       ...,
       [0],
       [0],
       [0]], dtype=int64)

In [58]:
model = Sequential()
model.add(Dense(1, input_shape=(1,)))

In [59]:
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_1 (Dense)              (None, 1)                 2         
Total params: 2
Trainable params: 2
Non-trainable params: 0
_________________________________________________________________


In [65]:
model.compile(Adam(lr=0.1),'mean_squared_error')

In [66]:
model.fit(A,I, epochs=20)

Epoch 1/20
17898/17898 [==============================] - 3s 144us/step - loss: 0.8918
Epoch 2/20
17898/17898 [==============================] - 1s 61us/step - loss: 0.0716
Epoch 3/20
17898/17898 [==============================] - 1s 54us/step - loss: 0.0930
Epoch 4/20
17898/17898 [==============================] - 1s 51us/step - loss: 0.2036
Epoch 5/20
17898/17898 [==============================] - 1s 51us/step - loss: 0.1889
Epoch 6/20
17898/17898 [==============================] - 1s 55us/step - loss: 0.1834
Epoch 7/20
17898/17898 [==============================] - 1s 51us/step - loss: 0.1789
Epoch 8/20
17898/17898 [==============================] - 1s 51us/step - loss: 0.1716
Epoch 9/20
17898/17898 [==============================] - 1s 52us/step - loss: 0.1479
Epoch 10/20
17898/17898 [==============================] - 1s 55us/step - loss: 0.2267
Epoch 11/20
17898/17898 [==============================] - 1s 53us/step - loss: 0.1992
Epoch 12/20
17898/17898 [==========================